### ISSUE TITLE
Doesn't display correctly if used on a small terminal window

### ISSUE THREAD

**Issue by dawnonmercury** [FrenzyExists/frenzch.sh#6]
When the command is used on a half screen sized terminal or less, the fetch only draws the very bottom of the display. Changing the size of the window after the command is used does not fix the display. When the command is used in a full screen sized window, it displays properly, despite resizing.
![Command on a small term window](https://user-images.githubusercontent.com/87095666/131231101-258b0cca-f751-483d-88b7-043319f41947.png)

![command on a full screen window](https://user-images.githubusercontent.com/87095666/131231113-13fe1d9d-7a61-4ec9-b7b6-988bfd27cf58.png)

**Comment by FrenzyExists** [comment]
No prob, I'll check it right away :+1:

**Comment by FrenzyExists** [comment]
Hey! Ok, good news, I think I fixed the issue. The first screenshot was the medium fetch, which I left half-done and didn't realized it got caught in the latest commit :facepalm:. But now its finished and I think it should look better. Give it a try and let me know if its working or not :+1:

**Comment by dawnonmercury** [comment]
sweet, it works as intended now
![2021-08-29-131444_539x585_scrot](https://user-images.githubusercontent.com/87095666/131248523-978ed432-c548-4495-9a19-faa4e9f82efc.png)
