### ISSUE TITLE
Invisible shell after using it

### ISSUE THREAD

**Issue by UnknownER0** [FrenzyExists/frenzch.sh#7]
After using it my shell has become invisible because i don't use a panel i guess and it freaked out

**Comment by FrenzyExists** [comment]
Don't worry, fixed the issue, I didn't reset the colors in the medium fetch and therefore the last color, being black, override the prompt, wouldn't notice if i didn't switched to bash for a moment

![image](https://user-images.githubusercontent.com/47986470/131237952-7e302ca3-d2e4-4270-83c0-f5e62d4974d5.png)

Here's how it would look
